version: '3'
services:
  web:
    container_name: web
    volumes:
      - /opt/app:/opt/app/
      - /opt/app/node_modules/
    ports:
      - '80:80'
    links:
      - postgres
    env_file:
      - db.env
    build: .
    command: "node index.js"
    depends_on:
      - postgres

  postgres:
    image: postgres:11-alpine
    container_name: db
    volumes:
      - /opt/app/db/:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    env_file:
      - db.env
